#pragma once

#define A3D_PP_BYTE_UNPACK(byte) A3D_PP_BYTE_UNPACK_REPARSE(A3D_PP_BYTE_UNPACK_EXP, byte)
#define A3D_PP_BYTE_UNPACK_EXP(p7,p6,p5,p4,p3,p2,p1,p0) p7,p6,p5,p4,p3,p2,p1,p0

#define A3D_PP_BYTE_UNPACK_REPARSE(x, y) A3D_PP_BYTE_UNPACK_REPARSE_STEP1(x, y)
#define A3D_PP_BYTE_UNPACK_REPARSE_STEP1(x, y) A3D_PP_BYTE_UNPACK_REPARSE_STEP2(x##y)
#define A3D_PP_BYTE_UNPACK_REPARSE_STEP2(result) result

