#pragma once

#include<core/preprocessor/bool_if.h>
#include<core/preprocessor/bool_or.h>
#include<core/preprocessor/uint8_equal.h>
#include<core/preprocessor/uint8_is_zero.h>
#include<core/preprocessor/uint8_less.h>
#include<core/preprocessor/uint8_sub_n.h>
#include<core/preprocessor/uint8_add_n.h>

/**
*  use for generating non-comma splited pattern code
*  start/end locate in [0,255] and start!=end
*  N range in  [start, end)
*  generate prefix + N + suffix + split pattern code (last item split will not appear)
*
*  e.g.  A3D_PP_REPEAT_RANGE_SPLIT(a, 0, 4, A3D_PP_NULL, | ) will generate
*  typename T0, typename T1, typename T2, typename T3
*/
#define A3D_PP_REPEAT_RANGE_SPLIT(prefix, start, end, suffix, split)    \
			A3D_PP_REPEAT_RANGE_SPLIT_STEP(prefix, start, end, 1, suffix, split)

//if    start == end or step == 0 return directly
//else  compare start and end
#define A3D_PP_REPEAT_RANGE_SPLIT_STEP(prefix, start, end, step, suffix, split)                     \
			A3D_PP_IF(  A3D_PP_OR( A3D_PP_EQUAL(start, end), A3D_PP_IS_ZERO(step)),    \
				A3D_PP_REPEAT_RANGE_SPLIT_END,                                                      \
				A3D_PP_REPEAT_RANGE_SPLIT_CMP)##(prefix, start, end, step, suffix, split)    

//return directly
#define A3D_PP_REPEAT_RANGE_SPLIT_END(...)

//if from < to do small to big   loop
//else         do big   to small loop
#define A3D_PP_REPEAT_RANGE_SPLIT_CMP(prefix, start, end, step, suffix, split)                      \
			A3D_PP_IF( A3D_PP_LESS(start, end),                                        \
				A3D_PP_REPEAT_RANGE_SPLIT_SMALL_TO_BIG,                                             \
				A3D_PP_REPEAT_RANGE_SPLIT_BIG_TO_SMALL)##(prefix, start, end, step, suffix, split) \

// do small to  big loop
#define A3D_PP_REPEAT_RANGE_SPLIT_SMALL_TO_BIG(prefix, start, end, step, suffix, split)    \
			A3D_PP_REPEAT_RANGE_SPLIT_LOOP_START(prefix, A3D_PP_SUB(end, start),          \
				start, step, suffix, split, A3D_PP_ADD )

// do big to small loop
#define A3D_PP_REPEAT_RANGE_SPLIT_BIG_TO_SMALL(prefix, start, end, step, suffix, split)   \
			A3D_PP_REPEAT_RANGE_SPLIT_LOOP_START(prefix, A3D_PP_SUB(start, end),          \
				start, step, suffix, split, A3D_PP_SUB)

// loop start
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP_START(prefix, count, N, step, suffix, split, op)   \
			A3D_PP_REPEAT_RANGE_SPLIT_LOOP_START2(prefix, count, N, step, suffix, split, op)

#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP_START2(prefix, count, N, step, suffix, split, op) \
			A3D_PP_REPEAT_RANGE_SPLIT_LOOP##count##(prefix, N, step, suffix, split, op)

// connect prefix+ N + suffix
#define A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix, N, suffix) A3D_PP_REPEAT_RANGE_SPLIT_CONNECT2(prefix, N, suffix)
#define A3D_PP_REPEAT_RANGE_SPLIT_CONNECT2(prefix, N, suffix) prefix##N##suffix

#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP1(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP2(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP1(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP3(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP2(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP4(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP3(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP5(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP4(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP6(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP5(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP7(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP6(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP8(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP7(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP9(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP8(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP10(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP9(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP11(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP10(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP12(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP11(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP13(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP12(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP14(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP13(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP15(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP14(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP16(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP15(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP17(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP16(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP18(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP17(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP19(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP18(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP20(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP19(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP21(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP20(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP22(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP21(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP23(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP22(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP24(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP23(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP25(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP24(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP26(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP25(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP27(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP26(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP28(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP27(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP29(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP28(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP30(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP29(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP31(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP30(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP32(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP31(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP33(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP32(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP34(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP33(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP35(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP34(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP36(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP35(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP37(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP36(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP38(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP37(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP39(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP38(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP40(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP39(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP41(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP40(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP42(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP41(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP43(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP42(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP44(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP43(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP45(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP44(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP46(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP45(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP47(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP46(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP48(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP47(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP49(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP48(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP50(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP49(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP51(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP50(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP52(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP51(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP53(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP52(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP54(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP53(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP55(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP54(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP56(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP55(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP57(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP56(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP58(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP57(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP59(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP58(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP60(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP59(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP61(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP60(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP62(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP61(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP63(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP62(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP64(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP63(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP65(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP64(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP66(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP65(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP67(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP66(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP68(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP67(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP69(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP68(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP70(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP69(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP71(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP70(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP72(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP71(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP73(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP72(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP74(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP73(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP75(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP74(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP76(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP75(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP77(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP76(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP78(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP77(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP79(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP78(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP80(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP79(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP81(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP80(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP82(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP81(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP83(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP82(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP84(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP83(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP85(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP84(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP86(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP85(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP87(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP86(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP88(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP87(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP89(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP88(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP90(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP89(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP91(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP90(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP92(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP91(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP93(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP92(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP94(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP93(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP95(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP94(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP96(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP95(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP97(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP96(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP98(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP97(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP99(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP98(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP100(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP99(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP101(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP100(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP102(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP101(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP103(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP102(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP104(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP103(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP105(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP104(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP106(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP105(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP107(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP106(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP108(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP107(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP109(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP108(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP110(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP109(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP111(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP110(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP112(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP111(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP113(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP112(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP114(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP113(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP115(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP114(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP116(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP115(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP117(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP116(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP118(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP117(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP119(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP118(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP120(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP119(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP121(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP120(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP122(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP121(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP123(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP122(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP124(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP123(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP125(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP124(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP126(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP125(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP127(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP126(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP128(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP127(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP129(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP128(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP130(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP129(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP131(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP130(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP132(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP131(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP133(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP132(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP134(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP133(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP135(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP134(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP136(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP135(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP137(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP136(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP138(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP137(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP139(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP138(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP140(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP139(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP141(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP140(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP142(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP141(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP143(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP142(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP144(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP143(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP145(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP144(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP146(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP145(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP147(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP146(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP148(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP147(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP149(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP148(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP150(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP149(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP151(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP150(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP152(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP151(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP153(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP152(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP154(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP153(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP155(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP154(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP156(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP155(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP157(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP156(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP158(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP157(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP159(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP158(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP160(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP159(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP161(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP160(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP162(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP161(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP163(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP162(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP164(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP163(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP165(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP164(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP166(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP165(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP167(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP166(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP168(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP167(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP169(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP168(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP170(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP169(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP171(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP170(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP172(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP171(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP173(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP172(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP174(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP173(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP175(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP174(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP176(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP175(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP177(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP176(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP178(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP177(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP179(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP178(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP180(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP179(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP181(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP180(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP182(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP181(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP183(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP182(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP184(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP183(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP185(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP184(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP186(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP185(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP187(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP186(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP188(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP187(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP189(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP188(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP190(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP189(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP191(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP190(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP192(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP191(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP193(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP192(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP194(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP193(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP195(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP194(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP196(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP195(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP197(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP196(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP198(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP197(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP199(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP198(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP200(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP199(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP201(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP200(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP202(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP201(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP203(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP202(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP204(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP203(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP205(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP204(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP206(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP205(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP207(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP206(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP208(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP207(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP209(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP208(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP210(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP209(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP211(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP210(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP212(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP211(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP213(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP212(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP214(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP213(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP215(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP214(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP216(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP215(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP217(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP216(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP218(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP217(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP219(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP218(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP220(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP219(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP221(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP220(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP222(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP221(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP223(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP222(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP224(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP223(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP225(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP224(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP226(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP225(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP227(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP226(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP228(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP227(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP229(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP228(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP230(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP229(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP231(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP230(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP232(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP231(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP233(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP232(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP234(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP233(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP235(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP234(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP236(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP235(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP237(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP236(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP238(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP237(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP239(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP238(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP240(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP239(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP241(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP240(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP242(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP241(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP243(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP242(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP244(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP243(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP245(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP244(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP246(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP245(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP247(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP246(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP248(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP247(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP249(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP248(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP250(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP249(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP251(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP250(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP252(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP251(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP253(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP252(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP254(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP253(prefix, op(N, step), step, suffix, split, op)
#define A3D_PP_REPEAT_RANGE_SPLIT_LOOP255(prefix, N, step, suffix, split, op)  A3D_PP_REPEAT_RANGE_SPLIT_CONNECT(prefix,N, suffix) split  A3D_PP_REPEAT_RANGE_SPLIT_LOOP254(prefix, op(N, step), step, suffix, split, op)

