#pragma once

#include<core/preprocessor/bool_if.h>
#include<core/preprocessor/bool_or.h>
#include<core/preprocessor/uint8_equal.h>
#include<core/preprocessor/uint8_is_zero.h>
#include<core/preprocessor/uint8_less.h>
#include<core/preprocessor/uint8_sub_n.h>
#include<core/preprocessor/uint8_add_n.h>

/**
 *  use for generating comma(,) splited pattern code 
 *  start/end locate in [0,255] and start!=end
 *  N range in  [start, end)
 *  generate prefix + N + suffix + , pattern code (last item , will not appear)
 *  
 *  e.g.  A3D_PP_REPEAT_RANGE(typename T, 0, 4, A3D_PP_NULL) will generate
 *  typename T0, typename T1, typename T2, typename T3
 */
#define A3D_PP_REPEAT_RANGE(prefix, start, end, suffix)    \
			A3D_PP_REPEAT_RANGE_STEP(prefix, start, end, 1, suffix)

//if    start == end or step == 0 return directly
//else  compare start and end
#define A3D_PP_REPEAT_RANGE_STEP(prefix, start, end, step, suffix)                     \
			A3D_PP_IF(  A3D_PP_OR( A3D_PP_EQUAL(start, end), A3D_PP_IS_ZERO(step)),    \
				A3D_PP_REPEAT_RANGE_END,                                               \
				A3D_PP_REPEAT_RANGE_CMP)##(prefix, start, end, step, suffix)    

//return directly
#define A3D_PP_REPEAT_RANGE_END(...)

//if from < to do small to big   loop
//else         do big   to small loop
#define A3D_PP_REPEAT_RANGE_CMP(prefix, start, end, step, suffix)                      \
			A3D_PP_IF( A3D_PP_LESS(start, end),                                        \
				A3D_PP_REPEAT_RANGE_SMALL_TO_BIG,                                      \
				A3D_PP_REPEAT_RANGE_BIG_TO_SMALL)##(prefix, start, end, step, suffix)  \

// do small to  big loop
#define A3D_PP_REPEAT_RANGE_SMALL_TO_BIG(prefix, start, end, step, suffix)   \
			A3D_PP_REPEAT_RANGE_LOOP_START(prefix, A3D_PP_SUB(end, start),   \
				start, step, suffix, A3D_PP_ADD )

// do big to small loop
#define A3D_PP_REPEAT_RANGE_BIG_TO_SMALL(prefix, start, end, step, suffix)   \
			A3D_PP_REPEAT_RANGE_LOOP_START(prefix, A3D_PP_SUB(start, end),   \
				start, step, suffix,  A3D_PP_SUB)

// loop start
#define A3D_PP_REPEAT_RANGE_LOOP_START(prefix, count, N, step, suffix, op)   \
			A3D_PP_REPEAT_RANGE_LOOP_START2(prefix, count, N, step, suffix, op)

#define A3D_PP_REPEAT_RANGE_LOOP_START2(prefix, count, N, step, suffix, op) \
			A3D_PP_REPEAT_RANGE_LOOP##count##(prefix, N, step, suffix, op)

// connect prefix+ N + suffix
#define A3D_PP_REPEAT_RANGE_CONNECT(prefix, N, suffix) A3D_PP_REPEAT_RANGE_CONNECT2(prefix, N, suffix)
#define A3D_PP_REPEAT_RANGE_CONNECT2(prefix, N, suffix) prefix##N##suffix

#define A3D_PP_REPEAT_RANGE_LOOP1(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix)
#define A3D_PP_REPEAT_RANGE_LOOP2(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP1(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP3(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP2(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP4(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP3(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP5(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP4(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP6(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP5(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP7(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP6(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP8(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP7(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP9(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP8(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP10(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP9(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP11(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP10(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP12(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP11(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP13(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP12(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP14(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP13(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP15(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP14(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP16(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP15(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP17(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP16(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP18(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP17(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP19(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP18(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP20(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP19(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP21(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP20(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP22(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP21(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP23(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP22(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP24(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP23(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP25(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP24(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP26(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP25(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP27(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP26(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP28(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP27(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP29(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP28(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP30(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP29(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP31(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP30(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP32(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP31(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP33(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP32(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP34(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP33(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP35(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP34(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP36(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP35(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP37(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP36(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP38(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP37(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP39(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP38(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP40(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP39(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP41(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP40(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP42(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP41(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP43(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP42(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP44(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP43(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP45(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP44(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP46(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP45(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP47(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP46(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP48(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP47(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP49(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP48(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP50(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP49(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP51(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP50(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP52(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP51(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP53(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP52(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP54(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP53(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP55(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP54(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP56(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP55(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP57(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP56(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP58(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP57(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP59(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP58(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP60(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP59(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP61(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP60(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP62(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP61(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP63(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP62(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP64(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP63(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP65(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP64(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP66(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP65(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP67(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP66(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP68(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP67(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP69(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP68(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP70(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP69(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP71(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP70(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP72(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP71(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP73(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP72(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP74(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP73(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP75(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP74(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP76(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP75(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP77(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP76(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP78(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP77(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP79(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP78(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP80(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP79(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP81(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP80(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP82(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP81(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP83(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP82(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP84(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP83(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP85(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP84(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP86(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP85(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP87(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP86(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP88(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP87(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP89(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP88(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP90(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP89(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP91(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP90(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP92(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP91(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP93(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP92(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP94(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP93(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP95(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP94(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP96(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP95(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP97(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP96(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP98(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP97(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP99(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP98(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP100(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP99(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP101(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP100(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP102(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP101(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP103(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP102(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP104(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP103(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP105(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP104(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP106(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP105(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP107(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP106(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP108(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP107(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP109(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP108(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP110(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP109(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP111(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP110(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP112(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP111(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP113(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP112(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP114(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP113(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP115(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP114(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP116(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP115(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP117(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP116(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP118(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP117(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP119(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP118(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP120(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP119(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP121(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP120(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP122(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP121(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP123(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP122(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP124(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP123(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP125(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP124(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP126(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP125(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP127(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP126(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP128(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP127(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP129(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP128(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP130(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP129(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP131(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP130(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP132(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP131(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP133(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP132(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP134(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP133(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP135(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP134(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP136(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP135(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP137(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP136(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP138(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP137(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP139(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP138(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP140(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP139(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP141(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP140(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP142(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP141(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP143(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP142(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP144(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP143(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP145(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP144(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP146(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP145(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP147(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP146(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP148(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP147(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP149(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP148(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP150(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP149(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP151(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP150(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP152(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP151(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP153(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP152(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP154(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP153(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP155(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP154(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP156(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP155(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP157(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP156(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP158(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP157(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP159(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP158(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP160(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP159(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP161(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP160(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP162(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP161(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP163(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP162(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP164(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP163(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP165(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP164(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP166(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP165(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP167(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP166(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP168(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP167(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP169(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP168(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP170(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP169(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP171(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP170(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP172(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP171(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP173(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP172(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP174(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP173(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP175(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP174(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP176(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP175(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP177(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP176(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP178(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP177(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP179(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP178(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP180(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP179(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP181(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP180(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP182(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP181(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP183(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP182(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP184(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP183(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP185(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP184(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP186(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP185(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP187(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP186(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP188(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP187(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP189(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP188(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP190(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP189(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP191(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP190(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP192(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP191(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP193(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP192(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP194(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP193(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP195(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP194(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP196(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP195(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP197(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP196(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP198(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP197(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP199(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP198(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP200(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP199(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP201(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP200(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP202(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP201(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP203(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP202(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP204(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP203(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP205(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP204(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP206(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP205(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP207(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP206(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP208(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP207(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP209(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP208(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP210(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP209(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP211(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP210(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP212(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP211(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP213(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP212(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP214(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP213(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP215(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP214(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP216(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP215(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP217(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP216(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP218(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP217(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP219(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP218(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP220(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP219(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP221(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP220(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP222(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP221(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP223(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP222(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP224(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP223(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP225(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP224(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP226(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP225(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP227(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP226(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP228(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP227(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP229(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP228(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP230(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP229(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP231(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP230(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP232(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP231(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP233(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP232(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP234(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP233(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP235(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP234(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP236(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP235(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP237(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP236(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP238(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP237(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP239(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP238(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP240(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP239(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP241(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP240(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP242(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP241(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP243(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP242(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP244(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP243(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP245(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP244(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP246(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP245(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP247(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP246(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP248(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP247(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP249(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP248(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP250(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP249(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP251(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP250(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP252(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP251(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP253(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP252(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP254(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP253(prefix, op(N, step), step, suffix, op)
#define A3D_PP_REPEAT_RANGE_LOOP255(prefix, N, step, suffix, op)  A3D_PP_REPEAT_RANGE_CONNECT(prefix,N, suffix),  A3D_PP_REPEAT_RANGE_LOOP254(prefix, op(N, step), step, suffix, op)

